E:\Tutorials\automate>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 175, in __init__
    self.service.start()
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 175, in __init__
    self.service.start()
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

>>> browser = webdriver.Chrome()
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 175, in __init__
    self.service.start()
  File "C:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

>>> browser = webdriver.Firefox()
>>> browser = webdriver.Firefox()
>>> type(browser)
<class 'selenium.webdriver.firefox.webdriver.WebDriver'>
>>> browser.get("https://inventwithpython.com")
>>> try:\
...
KeyboardInterrupt
>>>
>>> try:
...     elem = browser.find_element_by_class_name(" cover-thumb")
...     print("Found <%s> element with that class name!" % (elem.tag_name))
... except:
...     print("Was not able to find an element with that name.")
...
<stdin>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Was not able to find an element with that name.
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>> try:
...     elem = browser.find_element_by_class_name("cover-thumb")
...     print("Found <%s> element with that class name!" % (elem.tag_name))
... except:
...     print("Was not able to find an element with that name.")
...
Was not able to find an element with that name.
>>> try:
...     elem = browser.find_element_by_class_name("card-img-top cover-thumb")
...     print("Was not able to find an element with that name.")
... except:
...     print("Was not able to find an element with that name.")
...
Was not able to find an element with that name.
>>> try:
...     elem = browser.find_element_by_class_name("card-img-top cover-thumb")
...     print("Found <%s> element with that class name!" % (elem.tag_name))
... except:
...     print("Was not able to find an element with that name.")
...
Was not able to find an element with that name.
>>> try:
...     elem = browser.find_element_by_class_name(' cover-thumb')
...     print("Found <%s> element with that class name!" % (elem.tag_name))
... except:
...     print("Was not able to find an element with that name.")
...
Was not able to find an element with that name.
>>> browser = webdriver.Firefox()
>>> browser.get("https://inventwithpython.com")
>>> try:
...     elem = browser.find_element_by_class_name(' cover-thumb')
...     print(f"Found <{elem}> element with that class name!")
... except:
...     print("Was not able to find an element with that name.")
...
Was not able to find an element with that name.
>>> try:
...     elem = browser.find_element_by_class_name('jumbotron')
...     print(f"Found <{elem}> element with that class name!")
... except:
...     print("Was not able to find an element with that name.")
...
Found <<selenium.webdriver.remote.webelement.WebElement (session="ec086f18-5250-429c-b08b-340ff501861e", element="c85a8072-8577-4786-a0b8-f6a65a81933f")>> element with that class name!
>>> try:
...     elem = browser.find_element_by_class_name(' cover-thumb')
...     print(f"Found <{elem}> element with that class name!")
... except:
...     print("Was not able to find an element with that name.")
...
Was not able to find an element with that name.
>>> linkElem = browser.find_element_by_link_text("Read Online for Free")
<stdin>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
>>> linkElem = browser.find_element("Read Online for Free")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: unknown variant `Read Online for Free`, expected one of `css selector`, `link text`, `partial link text`, `tag name`, `xpath` at line 1 column 32

>>> linkElem = browser.find_element_by_link_text("Read Online for Free")
>>> type(linkElem)
<class 'selenium.webdriver.remote.webelement.WebElement'>
>>> linkElem.click()
>>> browser = webdriver.Chrome()

DevTools listening on ws://127.0.0.1:65096/devtools/browser/df5c0de8-f667-41ef-9173-25fd76001894
>>> [24424:10584:1023/181823.261:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[24424:10584:1023/181823.263:ERROR:chrome_browser_main_extra_parts_metrics.cc(233)] crbug.com/1216328: Checking Bluetooth availability ended.
[24424:10584:1023/181823.263:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[24424:14044:1023/181823.272:ERROR:device_event_log_impl.cc(214)] [18:18:23.272] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[24424:10584:1023/181823.276:ERROR:chrome_browser_main_extra_parts_metrics.cc(240)] crbug.com/1216328: Checking default browser status ended.
browser.get("https://messenger.com")
>>> userElem = browser.find_element_by_id("email")
>>> userElem.send_keys("rcpery@yahoo.com")
>>> password = browser[11016:6896:1023/182020.877:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is
^C
E:\Tutorials\automate>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> browser = webdriver.Chrome()

DevTools listening on ws://127.0.0.1:49764/devtools/browser/a756d2da-a66e-4e80-9633-51dcb47ef1ae
>>> browser.get("https://messenger.com") me_browser_main_extra_parts_metrics.cc(230)] crbug.com/1216328: Checking Blueto
Traceback (most recent call last):eport if there is no report that this ends.
  File "<stdin>", line 1, in <module>e_browser_main_extra_parts_metrics.cc(233)] crbug.com/1216328: Checking Bluetooth a
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in get
    self.execute(Command.GET, {'url': url})ser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default bro
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 416, in execute
    response = self.command_executor.execute(driver_command, params)1:24.206] Bluetooth: bluetooth_adapter_winrt.cc:1073
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 398, in execute
    return self._request(command_info[0], url, body=data)_parts_metrics.cc(240)] crbug.com/1216328: Checking default bro
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 420, in _request           b
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Python39\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "C:\Python39\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python39\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python39\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "C:\Python39\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "C:\Python39\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
>>>
>>> browser = webdriver.Chrome()

DevTools listening on ws://127.0.0.1:51233/devtools/browser/cc1153f5-5f50-4eb8-8ebf-0faf2e5c70e2
>>> [10840:22980:1023/182215.051:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[10840:22980:1023/182215.051:ERROR:chrome_browser_main_extra_parts_metrics.cc(233)] crbug.com/1216328: Checking Bluetooth availability ended.
[10840:22980:1023/182215.053:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[10840:17756:1023/182215.058:ERROR:device_event_log_impl.cc(214)] [18:22:15.058] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[10840:22980:1023/182215.068:ERROR:chrome_browser_main_extra_parts_metrics.cc(240)] crbug.com/1216328: Checking default browser status ended.
browser.get("https://messenger.com")
>>> userElem = browser.find_element_by_id("email")
<stdin>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
>>> passElem = browser.find_element_by_id("pass")
>>> userElem.send_keys("rcpery@yahoo.com")
>>> passElem.send_keys("p@rD()nMySw@G")
>>> passElem.submit()
>>> [18532:10708:1023/182412.709:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is
passElem.send_keys("cH@nGE003")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 539, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=95.0.4638.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x0042B9D3+2472403]
        Ordinal0 [0x003C6961+2058593]
        Ordinal0 [0x002D22B8+1057464]
        Ordinal0 [0x002D49E4+1067492]
        Ordinal0 [0x002D48AE+1067182]
        Ordinal0 [0x002D4B10+1067792]
        Ordinal0 [0x002FD019+1232921]
        Ordinal0 [0x002FD0F4+1233140]
        Ordinal0 [0x002F5A49+1202761]
        Ordinal0 [0x00315593+1332627]
        Ordinal0 [0x002F3236+1192502]
        Ordinal0 [0x0031567A+1332858]
        Ordinal0 [0x0032495F+1395039]
        Ordinal0 [0x0031545B+1332315]
        Ordinal0 [0x002F1FB4+1187764]
        Ordinal0 [0x002F2E09+1191433]
        GetHandleVerifier [0x005B3396+1551078]
        GetHandleVerifier [0x0065D53A+2247818]
        GetHandleVerifier [0x004B7FBB+521995]
        GetHandleVerifier [0x004B7079+518089]
        Ordinal0 [0x003CBD4D+2080077]
        Ordinal0 [0x003CFC18+2096152]
        Ordinal0 [0x003CFD52+2096466]
        Ordinal0 [0x003D94B1+2135217]
        BaseThreadInitThunk [0x7614FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76F77A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76F77A6E+238]

>>> browser.get("https://messenger.com")
>>> userElem = browser.find_element_by_id("email")
>>> passElem = browser.find_element_by_id("pass")
>>> userElem.send_keys("rcpery@yahoo.com")
>>> passElem.send_keys("cH@nGE003")
>>> passElem.submit()
>>> logOut = browser.find_element_by_class("oajrlxb2 g5ia77u1 qu0x051f esr5mh6w e9989ue4 r7d6kgcz rq0escxv nhd2j8a9 j83agx80 p7hjln8o kvgmc6g5 opuu4ng7 oygrvhab kj2yoqh6 cxgpxx05 dflh9lhu sj5x9vvc scb9dxdr i1ao9s8h esuyzwwr f1sip0of lzcic4wl n00je7tq arfg74bv qs9ysxi8 k77z8yql l9j0dhe7 abiwlrkh p8dawk7l bp9cbjyn dwo3fsh8 btwxx1t3 pfnyh3mw du4w35lb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'WebDriver' object has no attribute 'find_element_by_class'
>>> logOut = browser.find_element_by_class_name("oajrlxb2 g5ia77u1 qu0x051f esr5mh6w e9989ue4 r7d6kgcz rq0escxv nhd2j8a9 j83agx80 p7hjln8o kvgmc6g5 opuu4ng7 oygrvhab kj2yoqh6 cxgpxx05 dflh9lhu sj5x9vvc scb9dxdr i1ao9s8h esuyzwwr f1sip0of lzcic4wl n00je7tq arfg74bv qs9ysxi8 k77z8yql l9j0dhe7 abiwlrkh p8dawk7l bp9cbjyn dwo3fsh8 btwxx1t3 pfnyh3mw du4w35lb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 754, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".oajrlxb2 g5ia77u1 qu0x051f esr5mh6w e9989ue4 r7d6kgcz rq0escxv nhd2j8a9 j83agx80 p7hjln8o kvgmc6g5 opuu4ng7 oygrvhab kj2yoqh6 cxgpxx05 dflh9lhu sj5x9vvc scb9dxdr i1ao9s8h esuyzwwr f1sip0of lzcic4wl n00je7tq arfg74bv qs9ysxi8 k77z8yql l9j0dhe7 abiwlrkh p8dawk7l bp9cbjyn dwo3fsh8 btwxx1t3 pfnyh3mw du4w35lb"}
  (Session info: chrome=95.0.4638.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x0042B9D3+2472403]
        Ordinal0 [0x003C6961+2058593]
        Ordinal0 [0x002D22B8+1057464]
        Ordinal0 [0x002FC68B+1230475]
        Ordinal0 [0x003265B2+1402290]
        Ordinal0 [0x003155CA+1332682]
        Ordinal0 [0x0032495F+1395039]
        Ordinal0 [0x0031545B+1332315]
        Ordinal0 [0x002F1FB4+1187764]
        Ordinal0 [0x002F2E09+1191433]
        GetHandleVerifier [0x005B3396+1551078]
        GetHandleVerifier [0x0065D53A+2247818]
        GetHandleVerifier [0x004B7FBB+521995]
        GetHandleVerifier [0x004B7079+518089]
        Ordinal0 [0x003CBD4D+2080077]
        Ordinal0 [0x003CFC18+2096152]
        Ordinal0 [0x003CFD52+2096466]
        Ordinal0 [0x003D94B1+2135217]
        BaseThreadInitThunk [0x7614FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76F77A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76F77A6E+238]

>>>
^C
E:\Tutorials\automate>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> from selenium.webdriver.common.keys import Keys
>>> browser = webdriver.Chrome()

DevTools listening on ws://127.0.0.1:56397/devtools/browser/e8f29868-cabb-4d5d-80b5-a17aad9d3998
>>> [11344:11060:1023/183607.170:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[11344:11060:1023/183607.170:ERROR:chrome_browser_main_extra_parts_metrics.cc(233)] crbug.com/1216328: Checking Bluetooth availability ended.
[11344:11060:1023/183607.173:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[11344:20868:1023/183607.178:ERROR:device_event_log_impl.cc(214)] [18:36:07.178] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[11344:11060:1023/183607.190:ERROR:chrome_browser_main_extra_parts_metrics.cc(240)] crbug.com/1216328: Checking default browser status ended.
browser.get("https://nostarch.com")
>>> htmlElem = browser.find_element_by_tag_name("html")
<stdin>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
>>> html.send_keys(Keys.END)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'html' is not defined
>>> htmlElem.send_keys(Keys.END)
>>> htmlElem.send_keys(Keys.HOME)
>>> browser.refresh[16000:19104:1023/183804.696:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is
()
>>> browser.refresh()
>>> browser.forward()
>>> browser.refresh()
>>> browser.back()
>>> browser.quit()
>>>
KeyboardInterrupt
>>>
>>> ^Z
